### ISSUE TITLE
create app:  core4.api.v1.request.standard.login.LoginHandler and LogoutHandler

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#100]
both endpoint deserve a single widget/app with
* logout functionality (see https://stackoverflow.com/questions/233507/how-to-log-out-user-from-web-site-using-basic-authentication)
* password change functionality

**Comment by m-rau** [comment]
this ticket can be closed. The login request handler now implements the login screen. Please verify and confirm by closing this ticket.

**Comment by marekmru** [comment]
Tested.
