### ISSUE TITLE
card overlaps its boarders within widgetmanager

### ISSUE THREAD

**Issue by MarkusKral** [plan-net/core4#104]
I created a new widget utilizing the "async def card()" method to generate an html card.
The html-card itself is very simple:

`<html><body> Data Exchange Widget </body></html>`

Expected behavior: 
The html-file should only be visible within the boarders of its card.

Actual behavior: 

![image](https://user-images.githubusercontent.com/14922626/65884740-a76dc080-e399-11e9-97c6-d24ddf029c9b.png)

As it can be seen, the "titlebar" with its functional buttons (widget help and open in new tab) is overlapped.

**Comment by m-rau** [comment]
@marekmru: Can you analyse? Is this still an issue? What is the required solution?

**Comment by marekmru** [comment]
I'm not sure what happened there. I suppose @MarkusKral  was just experimenting. 
In any case - the developer has the responsibility to adjust paddings so that the card content fits the card.
