### ISSUE TITLE
Apps with Navigation inside Widget Manager

### ISSUE THREAD

**Issue by marekmru** [plan-net/core4#106]
Current state
_CORE4os / CORE4ui apps/widgets have their own navigation bar. The navigation bar is also displayed inside the widget manager. As a result, two navigation bars are displayed within the widgetmanager._

Solution
The widget notices that it is inside the widget manager and additionally displays the known close button. The widgetmanager checks if the current widget is a CoreStaticFileHandler (only CoreStaticFileHandler widgets have an additional navigation) and hides its own navigation bar.
This gives the widget full control over navigation/validation, title. It makes no difference to the user.

The close button gets a function that allows to close the widget via postMessage or similar functions in the widgetmanager.

**Comment by marekmru** [comment]
After dischussion with @m-rau the decission was made to introduce a  new flag called spa: True|False

**Comment by m-rau** [comment]
created pull request #107 

### next step
* testing
* make changes to existing core4os endpoints

**Comment by m-rau** [comment]
@marekmru reported the issue, that the _spa_ attribute is not available with ``/_info`` endpoint. This has been fixed.
see branch ``develop``

**Comment by marekmru** [comment]
Done. FE now handles spa attribute correctly.
