### ISSUE TITLE
spa attribute should be displayed in API help screen

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#114]
this ticket relates to #72 and #106.
The new _spa_ attribute_ should be displayed in the API help screen.

**Comment by marekmru** [comment]
Pull request: https://github.com/plan-net/core4/pull/160

**Comment by MarkusKral** [comment]
Spa attribute exists now in the detail-screen of the widget help.
It behaves correctly when setting the attribute "spa = True" on a CoreRequestHandler.
