### ISSUE TITLE
Websocket Connections in Firefox (>65.0)

### ISSUE THREAD

**Issue by marekmru** [plan-net/core4#120]
The comoco webapp uses Websocket connections for retrieving job/system updates.
The firefox does not establish a websocket connection and therefore does not receive any updates.

**Comment by marekmru** [comment]
Ok, our test system is outdated- version 62 of firefox is installed there.
Websockets and Comoco work in current Version  (71.0 (November `19)) 
Imho this can be closed.

**Comment by m-rau** [comment]
so this ticket is denied. Needs to be resolved on client side by upgrading the browser.
