### ISSUE TITLE
persistence

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#125]
The following persistence has been implemented.

- [x] Sorting the columns
- [x] Visibility of the columns
- [x] Dense true false.
- [x] Elements per page

**Comment by m-rau** [comment]
has been implemented
* _dense_ (bool, default defined by BE developer)
* _per_page_ (int, default defined by BE developer)
* _column_ as list of dict with key _name_ and key _hide_ (bool), default defined by BE developer
* _sort_ as list of dict with key _name_ and key _ascending_ (bool), default defined by BE developer

additionally a _reset_ (bool) argument is processed to reset the above attributes to the default values

### next step
* finish documentation with examples for hand-over to FE developer team

**Comment by m-rau** [comment]
implemented and now included in response of GET and POST:
See documentation at ``CoreDataTable`` and ``CoreDataTableRequest``.
@marekmru: Ready for FE integratioin.

**Comment by OlhaTodorashko** [comment]
front-end: implemented in plan-net/core4fe.oto.121
