### ISSUE TITLE
search

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#127]
search can be enabled or disabled by the BE developer by _search_ (bool) attribute.
The passed _filter_ argument represents a string. It depends on the backend methods _.length_ and _.query_ how this string is processed, e.g. by json parsing.

**Comment by m-rau** [comment]
has been implemented. The very first implementation should work with strings only.

**Comment by m-rau** [comment]
implemented and now included in response of GET and POST:
See documentation at ``CoreDataTable`` and ``CoreDataTableRequest``.
@marekmru: Ready for FE integratioin.

**Comment by OlhaTodorashko** [comment]
front-end: implemented in plan-net/core4fe.oto.121
