### ISSUE TITLE
nowrap column attribute

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#128]
the BE sends a _nowrap_ attribute for each column, the frontend deactivates the breaks for each column using CSS.
```
columns : [
  {
    no_wrap; true, 
    width: 320, 
    hide: false, 
    click: false, 
    key: false, 
    format: "{}",
    ... 
  }
] 
```

**Comment by m-rau** [comment]
option has been added

**Comment by m-rau** [comment]
implemented and now included in response of GET and POST:
See documentation at ``CoreDataTable`` and ``CoreDataTableRequest``.
@marekmru: Ready for FE integratioin.

**Comment by OlhaTodorashko** [comment]
front-end: implemented in plan-net/core4fe.oto.121
