### ISSUE TITLE
export table

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#129]
Export to support CSV file format only.

**Comment by m-rau** [comment]
has been implemented

**Comment by m-rau** [comment]
implemented and now available with ``download=1``.
See documentation at ``CoreDataTable`` and ``CoreDataTableRequest``.
@marekmru: Ready for FE integratioin.

**Comment by OlhaTodorashko** [comment]
front-end: implemented in plan-net/core4fe.oto.121
