### ISSUE TITLE
show meta info

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#130]
* at bottom of table
* raw html

**Comment by m-rau** [comment]
_info_ attribute has been added (str)

**Comment by m-rau** [comment]
implemented and now included in response of GET and POST:
See documentation at ``CoreDataTable`` and ``CoreDataTableRequest``.
@marekmru: Ready for FE integratioin.

**Comment by OlhaTodorashko** [comment]
front-end: implemented in plan-net/core4fe.oto.121
