### ISSUE TITLE
show/hide footer

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#131]
* defaults to True (show)
* includes pagination

**Comment by m-rau** [comment]
option has been added

**Comment by m-rau** [comment]
implemented and now included in response of GET and POST:
See documentation at ``CoreDataTable`` and ``CoreDataTableRequest``.
@marekmru: Ready for FE integratioin.

**Comment by OlhaTodorashko** [comment]
front-end: implemented in plan-net/core4fe.oto.121
