### ISSUE TITLE
endpoint actions

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#133]
implemented with the following attributes
* icon
* method GET, POST, PUT, DELETE and the non-standard method FOLLOW
* endpoint
Please note that GET, POST, PUT and DELETE implement ajax requests. In contrast to this the non-standard action FOLLOW  instructs the browser to follow to a new location.

**Comment by m-rau** [comment]
implemented and now included in response of GET and POST:
See documentation at ``CoreDataTable`` and ``CoreDataTableRequest``

**Comment by OlhaTodorashko** [comment]
implemented in plan-net/core4fe.oto.121
