### ISSUE TITLE
Job flagged as killed is not being killed by the system

### ISSUE THREAD

**Issue by Flabicht** [plan-net/core4#137]
Job flagged as killed is not being killed by the system:

     1 running  Z..K datacloud.adwords.AdWordsCampaignPerformanceReportLoader

c.c. @m-rau

**Comment by m-rau** [comment]
A running job can only be killed by the operating worker. If the worker has been stopped or became unavailable, then there is no robust option to kill this running job.
To handle these edge cases, an option ``--remove-hard`` has been introduced with ``coco``. This command journals the job irrespective of the current job state. Please be aware that this option should be used only if you know what you are doing.
The option is available in core4os version 0.4.1
