### ISSUE TITLE
No umlauts allowed in Realname when creating new user or role

### ISSUE THREAD

**Issue by basteiz** [plan-net/core4#138]
role will be saved, but with this error message

![image](https://user-images.githubusercontent.com/8985128/69551138-7d510d00-0f9c-11ea-9ac3-470803899b3f.png)

**Comment by marekmru** [comment]
Please approve and close if fixed

**Comment by MarkusKral** [comment]
Hi @marekmru ,

where did you push those changes to? 
I cant find a referenced commit/branch or pull-request.

Cheers!
Markus

**Comment by m-rau** [comment]
cannot reproduce. Ticket considered resolved.
