### ISSUE TITLE
Provide contact E-Mail for Frontends

### ISSUE THREAD

**Issue by marekmru** [plan-net/core4#139]
Currently a hardcoded contact E-Mail is diplayed in some of the Error Dialogs. A configurable e_Mail should be provided to the Frontend. For example through a yaml setting.

**Comment by m-rau** [comment]
expected: the current, active application version number is displayed.
actual: always core4os version number is displayed

Furthermore the version is to be displayed in the help screen.

**Comment by m-rau** [comment]
requires fixing

**Comment by m-rau** [comment]
There are two alternative solutions:
1. implement a new endpoint to access (selected) elements from the yaml config
1. put a key/value pair into the existing user specific /settings endpoint. If the user has no custom settings for a specified attribute, then a default settings can be defined. This is the approach for the "language" setting as well as for the "app manager menu".

Option 2 has been developed with the idea in mind to provide user-specific settings as an _option_. For contact e-mail the same applies. The option to have a default _and_ user-specific contact emails allows the system to have user groups with seperate contact emails.

Therefore I suggest to implement option 1.

### next step
* adopt the default settings in ``core4.yaml``
* adopt all production settings in ``local.yaml``
* implement FE call to inquire contact email

**Comment by m-rau** [comment]
configuration changed in branch ``develop``. contact e-mail now comes with ``/setting`` endpoint.

**Comment by marekmru** [comment]
Feature added in develop.
Tested and approved
