### ISSUE TITLE
Remove button on widgets overlayed by sidebar

### ISSUE THREAD

**Issue by MarkusKral** [plan-net/core4#140]
even with the slimmest apperance of the sidebar for the widget-search, the close-bottun of widgets is overlayed:

![image](https://user-images.githubusercontent.com/14922626/69858559-9276b600-1292-11ea-8b91-8277a0cb1d26.png)

Can we adjust the area in which widgets are shown so that they do take the slimmest appreance of the sidebar into account?

**Comment by marekmru** [comment]
Please approve and close

**Comment by m-rau** [comment]
retest required

**Comment by KralMar** [comment]
There is no overlapping any longer if the sidebar is retracted.
This works over multiple window widths. 

Closing this ticket.
