### ISSUE TITLE
core4.util.email.RoleEmail errors when creating role without email

### ISSUE THREAD

**Issue by basteiz** [plan-net/core4#141]
When creating a role (without email address) an email.RoleEmail Job will be ensued and errors because no email address has been provided.

log:
```javascript
2019-11-25 15:28:43 CRITICAL core4@worker1.spm core4.util.email.RoleEmail@5ddbe519dd5ae25cf32857e5: done execution with [error] after [1] sec. and [0] attempts to go: TypeError("'NoneType' object is not iterable",)
Traceback (most recent call last):

  File "/srv/core4/home/core4/.venv/lib/python3.5/site-packages/core4/queue/process.py", line 84, in start
    job.execute(**job.args)

  File "/srv/core4/home/core4/.venv/lib/python3.5/site-packages/core4/util/email.py", line 126, in execute
    self.send_mail(to=recipients, subject=subject, message=message)

  File "/srv/core4/home/core4/.venv/lib/python3.5/site-packages/core4/util/email.py", line 99, in send_mail
    raise e

  File "/srv/core4/home/core4/.venv/lib/python3.5/site-packages/core4/util/email.py", line 95, in send_mail
    server.sendmail(sent_from, to, msg.as_string())

  File "/usr/lib/python3.5/smtplib.py", line 866, in sendmail
    for each in to_addrs:

TypeError: 'NoneType' object is not iterable
```

Arguments
```javascript
'args': {'realname': 'Lesezugriff auf Planet db',
          'recipients': None,
          'subject': 'core4: created user',
          'template': 'en/user_creation.txt',
          'token': TOKEN',
          'username': 'read_plannet'},

....
```

**Comment by m-rau** [comment]
cannot reproduce. Maybe this is rather a browser issue and not an app/backend issue.
Please verify.

**Comment by basteiz** [comment]
it exists exactly this error on prod right now:

this user (better role):
<img width="604" alt="image" src="https://user-images.githubusercontent.com/8985128/72936082-d6ec7280-3d66-11ea-9428-bf1f7d9c4f38.png">


and this details in job:

`coco --detail 5e258d174ae272d0fdcbfb4b
{'_hash': '2e088c5ec295ddea7498c50bc2538e3a',
 '_id': ObjectId('5e258d174ae272d0fdcbfb4b'),
 'args': {'realname': 'xo360 Audit Administrator',
          'recipients': None,
          'subject': 'core4: created user',
          'template': 'en/user_creation.txt',
          'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6bnVsbCwibmFtZSI6InhvMzYwX2FkbWluIiwiZXhwIjoxNTc5NTQ4MDU0fQ.lckuOXoUu6IM_RgRvfr26FU4Oe1A22DctU9B6vnTgTHmhNwpSbzRfNFv5-Eyg4YjU2Z0sZOLcnOL6T5YcJu4hw',
          'username': 'xo360_admin'},
 'attempts': 1,
 'attempts_left': 0,
 'chain': [],
 'defer_max': 3600,
 'defer_time': 300,
 'dependency': [],
 'enqueued': {'at': datetime.datetime(2020, 1, 20, 11, 20, 55, 873000),
              'hostname': 'app1.spm',
              'parent_id': None,
              'username': 'core4'},
 'error_time': 600,
 'finished_at': datetime.datetime(2020, 1, 20, 11, 20, 57, 372000),
 'force': False,
 'inactive_at': datetime.datetime(2020, 1, 20, 12, 20, 57, 213000),
 'killed_at': None,
 'last_error': {'exception': 'TypeError("\'NoneType\' object is not '
                             'iterable",)',
                'timestamp': datetime.datetime(2020, 1, 20, 11, 20, 57, 372000),
                'traceback': ['Traceback (most recent call last):\n',
                              '  File '
                              '"/srv/core4/home/core4/.venv/lib/python3.5/site-packages/core4/queue/process.py", '
                              'line 84, in start\n'
                              '    job.execute(**job.args)\n',
                              '  File '
                              '"/srv/core4/home/core4/.venv/lib/python3.5/site-packages/core4/util/email.py", '
                              'line 126, in execute\n'
                              '    self.send_mail(to=recipients, '
                              'subject=subject, message=message)\n',
                              '  File '
                              '"/srv/core4/home/core4/.venv/lib/python3.5/site-packages/core4/util/email.py", '
                              'line 99, in send_mail\n'
                              '    raise e\n',
                              '  File '
                              '"/srv/core4/home/core4/.venv/lib/python3.5/site-packages/core4/util/email.py", '
                              'line 95, in send_mail\n'
                              '    server.sendmail(sent_from, to, '
                              'msg.as_string())\n',
                              '  File "/usr/lib/python3.5/smtplib.py", line '
                              '866, in sendmail\n'
                              '    for each in to_addrs:\n',
                              "TypeError: 'NoneType' object is not "
                              'iterable\n']},
 'locked': None,
 'max_parallel': 15,
 'name': 'core4.util.email.RoleEmail',
 'priority': 0,
 'prog': {'message': None, 'value': None},
 'progress_interval': 5,
 'query_at': None,
 'removed_at': None,
 'runtime': 1.372,
 'sources': [],
 'started_at': datetime.datetime(2020, 1, 20, 11, 20, 56),
 'state': 'error',
 'trial': 1,
 'wall_at': None,
 'wall_time': None,
 'worker': None,
 'zombie_at': None,
 'zombie_time': 1800}`

**Comment by MarkusKral** [comment]
assigned after disucission with @m-rau

**Comment by m-rau** [comment]
bug confirmed. bug fixed.
