### ISSUE TITLE
role and user management widget - multiple bugs

### ISSUE THREAD

**Issue by basteiz** [plan-net/core4#145]
following points doesn't work:

* sorting columns
* rows per page doesnt have any effect
* possible to create users which differentiate only upper and lower case (example bzi and BZI)

**Comment by marekmru** [comment]
following points doesn't work:

sorting columns (/)
rows per page doesnt have any effect
possible to create users which differentiate only upper and lower case (example bzi and BZI)

**Comment by marekmru** [comment]
Status: It's fixed. Currently we have problems with deplyment

**Comment by marekmru** [comment]
search not case sensitive  :white_check_mark:
develop/master/ deployed on prod

**Comment by m-rau** [comment]
so what is the status here. I guess all has been implemented except case-insensitive usernames, because this is expected behavior.
Right?

**Comment by marekmru** [comment]
Imo it is fixed, but i wont close the ticket as the developer. Somebody should approve / test this.

**Comment by marekmru** [comment]
Bug: Chrome autocomplete captures some fields - email, password in creation dialog.

**Comment by marekmru** [comment]
autocomplete fixed n the filds email and password:
autocomplete="new-password"
autocomplete="new-email"

**Comment by marekmru** [comment]
Done.
