### ISSUE TITLE
role and user management - mixture of perm and roles

### ISSUE THREAD

**Issue by basteiz** [plan-net/core4#150]
at the moment the endpoint: /core4/api/v1/roles/

results data.perm the complete list of all permissions the user has, it combines the permissions and the permissions the user inherited from roles.
see:
![image](https://user-images.githubusercontent.com/8985128/70717075-eb603880-1ced-11ea-98e1-a9cb4ff67a0e.png)

results in db for comparison:

```Java
{
    "_id" : ObjectId("5dcad42271122b31e9835fca"),
    "realname" : "Basti z Test",
    "perm" : [],
    "is_active" : true,
    "password" : "$pbkdf2-sha256$29000$ca5Vak0pBQAghJCyVspZqw$GihpdXYyXwluQgKEOk45WbNhG26N0tWS2r6uU8pFBJo",
    "email" : "zimm",
    "etag" : ObjectId("5df23d583e50a378b400d3f0"),
    "created" : ISODate("2019-11-12T15:47:46.029Z"),
    "role" : [ 
        ObjectId("5dee1c8fa4296c2918197445"), 
        ObjectId("5dc3b53effc34e39a8e355f6"), 
        ObjectId("5ddbe51610333867f58829b1"), 
        ObjectId("5d0a34934ff00670fa3dd9e1")
    ],
    "name" : "bastiz_test",
    "last_login" : ISODate("2019-12-12T13:16:42.689Z"),
    "updated" : ISODate("2019-12-12T13:15:04.884Z")
}
```

wenn user now submits any change, all permissions in Block "perm" will be saved to sys.role collection.

when deleting role later, it doesn't have any effect, you need then to remove all perms separately.

@m-rau does this really make sense??

**Comment by basteiz** [comment]
Correct handling from my perspective would be that only the dedicated permissions will shown, but I thing that has an impact for permission handing in general!

**Comment by basteiz** [comment]
Proposal from my site would be, that we need a new field "perm_total" or "perm_view" for visualization in role and user management!

**Comment by m-rau** [comment]
has been merged
