### ISSUE TITLE
comoco must use wss instead of ws

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#155]
currently the comoco monitoring application is not working if served over https.
analysis, solution and fixing required.
First step here is to analyse, how the comoco front end application can dynamically decide if this is a wss or ws protocol. Describe the suggested solution here before implementation.

**Comment by OlhaTodorashko** [comment]
if (location.protocol != 'https:'){
 // use ws
} else {
 // use wss
}

**Comment by m-rau** [comment]
please implement

**Comment by m-rau** [comment]
has been implemented, see pull request #158

**Comment by m-rau** [comment]
not working

**Comment by OlhaTodorashko** [comment]
my fix is inside "develop" branch and as I can see on production we use the "master" branch -without my latest changes.

**Comment by KralMar** [comment]
This is not fixed in branch develop.

I can manually open a wss connection to the backend but comoco fails to do so.

**Comment by MarkusKral** [comment]
working with chrome. closing this issue.
