### ISSUE TITLE
change dashboard in widget manager

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#17]
All users of the widget manager have a default dashboard "Favorites". Users can add, rename and remove dashboards (including the Favorites). The current dashboard's title is rendered at the top of the screen. Switching between dashboards is to be implemented by a the previous and next dashboard. Call to action is by arrows or by dashboard titles.
Another idea is to represent the number of dashboards and the current dashboards as unfilled/filled circles at the bottom of the screen similar to android start screens.
The concrete decision and visualisation is to be decided.

**Comment by marekmru** [comment]
TODO (yet not implemented):
>  Another idea is to represent the number of dashboards and the current dashboards as unfilled/filled circles at the bottom of the screen similar to android start screens.

Please approve:
mmr.finetuning-2

**Comment by m-rau** [comment]
accepted.
Detail comment: it is not immediately obvious that the current dashboard cannot be removed.
Please create follow-up tickets on the pending actions and close this ticket afterwards.

**Comment by m-rau** [comment]
requires some testing
