### ISSUE TITLE
browser basic auth dialog pops up

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#177]
I have observed minimum 2 situations where the basic auth dialog of the browser interferes with the login mechanic of core4os.

1) if a session has been timed out and the user triggers an action in the app. See image attached.

![Bildschirmfoto 2020-03-19 um 10 41 26](https://user-images.githubusercontent.com/8707965/77053553-cce59980-69ce-11ea-9abc-62cb07ead37c.png)

2) initial login with firefox.

![Bildschirmfoto 2020-03-19 um 10 48 55](https://user-images.githubusercontent.com/8707965/77053927-5bf2b180-69cf-11ea-8f71-ea6683cf0e42.png)

Firefox browser is not supported but maybe the behavior helps identifying the issue.

**Comment by marekmru** [comment]
fixed
