### ISSUE TITLE
set_source() logging, fetching current source

### ISSUE THREAD

**Issue by sanikamnjoshi** [plan-net/core4#185]
### Description:
- set_source() function defined in core4/queue/job.py logs to self.logger.info every time it is called even when the source is the same as earlier.
- Additionally, there is no way to reliably fetch the most recently set source the way the function has been coded right now.
- Example:
```
# within a job:  
# set_source() hasn't been called yet -> # the property self.sources is currently: []
self.set_source('A')        # set_source() called for the first time -> self.sources is now ['A']
self.set_source('B')        # self.sources is now ['A', 'B']
self.set_source('A')        # set_source() called with 'A' as the source again -> self.sources is still ['A', 'B']
```
- Due to scenarios such as this one, self.sources[-1] won't essentially give us the current source.
- This means there is a bug in the get_source() function as well, as it returns self.sources[-1] (or None if no source has been set yet) as the current source.

### Resolution:
- A new property - say 'self.current_source' (Type: string, Default Value: None) - should be added which stores the source that is currently set with set_source().
- get_source() should return self.current_source and not self.sources[-1]
- With the help of this new property, logging in set_source() should be changed such that it logs only when a new source is set or when the source changes.

**Comment by m-rau** [comment]
merged into develop
