### ISSUE TITLE
app manager display subtitle, not qual_name

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#188]
The app manager must display the app's subtitle in the 2nd header below the title. The subtitle can be set for endpoints and static handlers. If no subtitle is defined, the subtitle defaults to the qual_name.
In search, both the subtitle _and_ the qual name are to be searched.

## action required
* backend fix
* widget manager fix

**Comment by marekmru** [comment]
https://github.com/plan-net/core4/pull/193
