### ISSUE TITLE
"Feature" request: Python Version upgrade 

### ISSUE THREAD

**Issue by Data-Mastery** [plan-net/core4#203]
Are there any plans to upgrade python to python >= 3.6? 
I think the modern  f-String syntax would make it way easier to write loggers.

**Comment by m-rau** [comment]
Have you tried core4 regression tests with python >= 3.6? If not, please do and post your observations.

**Comment by MarkusKral** [comment]
Hi,

I do use python 3.7 within my installation without any problems.
All tests succeed.

Cheers!

**Comment by m-rau** [comment]
but before we officially support it, we need to stage it.

**Comment by Data-Mastery** [comment]
ok thank you. Since production runs on your system I will wait for an official update.
