### ISSUE TITLE
restore recent widget manager view

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#21]
All users want the widget manager to restore the most recent view if he or she reenters the landing page.

**Comment by marekmru** [comment]
We should use the settings api for this. Similar to the light / dark mode the users widget app settings should be persisted and loaded on WidgetApp launch.

**Comment by marekmru** [comment]
Solved in https://github.com/plan-net/core4/pull/75

**Comment by m-rau** [comment]
to be reviewed in merge. this ticket closed.

**Comment by m-rau** [comment]
reopen. The setting "show/hide API widget" must be in scope of this feature, to.

**Comment by marekmru** [comment]
Resolved in mmr.c4os#21_2

**Comment by m-rau** [comment]
So can we close this ticket?

**Comment by MarkusKral** [comment]
I just tested with your suggested method and logging in and out.

Feature confirmed working, closing this ticket.
