### ISSUE TITLE
open widget standalone or embedded 

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#22]
Implement core4 handler attribute target with “blank” or None (defaults to None).
with `None` the user has the option to open the widget embedded in the widget manager or to open the widget without the widget manager in standalone mode.
With "blank" this behavior is enforced to open without the widget manager in standalone mode.

**Comment by m-rau** [comment]
target attribute:
- if None, then render embedded
- if "blank", then render with standalone

**Comment by marekmru** [comment]
changed in mmr.CORE4#25 (https://github.com/plan-net/core4/issues/22)

**Comment by m-rau** [comment]
has been merged into develop. See #40
