### ISSUE TITLE
implement widget search

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#23]
The plugin search of WebStorms (see [here](https://www.jetbrains.com/help/img/idea/2019.1/ws_plugins_settings.png)) is a very good blueprint. It provides autocompletion for the most relevant search attributes with dropdown boxes to facilitate widget search.
The following widget attributes are relevant to search:
- by title
- by subtitle (defaults to qual_name)
- by author (matching the username and real name)
- by tag
- by description

**Comment by m-rau** [comment]
has this been implemented? what has been implemented?

**Comment by marekmru** [comment]
- [ by title ]

**Comment by m-rau** [comment]
to be very clear: The qual_name should be added, since it is not available if the developer defines a subtitle.
Furthermore the qual_name of the container should be added. This allows for example searching for an account name (account name defined as the first part of the qual_name).

**Comment by m-rau** [comment]
for further carification: include the "container" attribute in the scope of search

**Comment by m-rau** [comment]
The ``container`` attributes needs to be added to the ``/_info`` endpoint. Including this attribute into the search is the solution to improve searching for handlers of a specific project. Without this solution, all handler classes defined outside of the project (e.g. CoreStaticFileHandler) will not be found with a search for the project name..

# action required

1. add ``container`` attribute to ``/_info`` (@m-rau)

1. include ``container`` attribute in FE search (@marekmru)

**Comment by MarkusKral** [comment]
Hi @marekmru:
I can confirm this within the current development-branch.
Can you please have a look at the widget search again?

**Comment by marekmru** [comment]
This is a feature. core4 is not used for searching because.

**Comment by MarkusKral** [comment]
I see that searching for other qual_names i possible.
Is there a special reason to explicitly exclude "core4"?

**Comment by marekmru** [comment]
Becuse 'core4' was basically everywhere. Thats why i excluded it.

**Comment by MarkusKral** [comment]
I do not like disabling the filtering for a specific project completely.
I see the problem that there are multiple APIs and Frontends (StaticFileHandler) found by searching for core4, however I think the APIs should pose no problem as all technical APIs can be excluded by the User. 
What remains is the Problem of StaticFileHandlers, by searching for core4 we would also include frontends of other projects as they all can be find via the StaticFileHandler qual_name (which includes core4).

@m-rau @marekmru :
any idea on howto tackle this? Maybe we should think about not including StaticFileHandlers within a search for "core4" but this feels inconsistent to me.

**Comment by m-rau** [comment]
My suggestion is to be consistent. Include the qual name into the search. 
Creating a good UX for searching can be realised only with a good search interface. Putting constraints and logic into the qual name itself or by exclusion of specific handlers does not lead to any good solution.

**Comment by marekmru** [comment]
qual_name included,
container included

Imo this can be closed
