### ISSUE TITLE
Docutils version incompatibility with Sphinx

### ISSUE THREAD

**Issue by sanikamnjoshi** [plan-net/core4#238]
- docutils came up with version 0.17 on april 3 and on april 11, sphinx restricted its requirements to docutils-0.**16** (ref [link](https://www.sphinx-doc.org/en/master/changes.html#id24))
-  now we get this error when trying to run any coco command after a fresh installation:
  `pkg_resources.ContextualVersionConflict: (docutils 0.17 (/home/sjo/dev/core4/.venv/lib/python3.5/site-packages), Requirement.parse('docutils<0.17,>=0.12'), {'Sphinx'})`
- Resolution: Need to change core4 requirements.txt to also restrict docutils to <0.17 (until sphinx starts supporting 0.17)

**Comment by m-rau** [comment]
rejected. The requirement needs to go into ```setup.py```.
Fixed in branch ```develop```. Additionally there were some hickups with ```rpy2```. I've been able to fix by "requiring" the ```cffi``` package in ```setup.py```, too.
