### ISSUE TITLE
implement widget and dashboard control

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#26]
Dashboard control is available as a right-side navigation bar. The left-side navigation bar is not in scope of the widget manager. It is in scope of the widget instead. 
We call this right-side navigation bar “widget manager” 
The widget manager in the right-side navigation bar features
- the widget listing
- the search including the search bar and the current filters
- the dashboard control access item (see below)

The widget manager has three sizes and the user can select between these:
- small size - the widget manager only lists the widgets, the quick access, a condensed search. The size is ~25%.
- medium size - the widget manager lists the widgets, the quick access, the search. The size is ~50%.
- large size  - the widget manager lists the widgets as cards, the quick access, the search. The size is ~90% or more.

**Comment by marekmru** [comment]
PLease approve: mmr.CORE4#26

**Comment by m-rau** [comment]
accepted.
