### ISSUE TITLE
implement custom links to widgets

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#33]
since additional features of the widget manager are to be implemented as widgets, these widgets must be accessible with the following call to actions
1. regular cards with their controls
1. from the search
1. from the all widget listing (as regular cards with their controls)
1. from links in the header bar
1. from items in the right-side menue in the header bar

The links in the header bar and menu must be customiisable. The customisation approach and OS version needs to be defined and implemented.

**Comment by m-rau** [comment]
1, 2, 3 have been implemented.
4, 5 are duplicate to #73 

This ticket can be closed

**Comment by m-rau** [comment]
if you agree please close the ticket

**Comment by KralMar** [comment]
agreed. 
Closing this ticket.
