### ISSUE TITLE
top left menu item in widget manager

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#35]
The top left menu bar is under control of the widget. It is not under control of the widget manager.
Refactor the main menu item.

**Comment by marekmru** [comment]
Part 1:
* Added a prop to cre4ui that handles the visibility of the icon
* Moved menu items to main aplication bar 

Part 2:
(Widget doesnt control navigation yet, as it is a more complex task (dev + concept))

**Comment by m-rau** [comment]
top left menu item and menu still visible. please confirm.

**Comment by marekmru** [comment]
on Production or localhost?

**Comment by m-rau** [comment]
Both.. Produktion und localhost.

Von: Markus Mrugalla <notifications@github.com>
Antworten an: plan-net/core4 <reply@reply.github.com>
Datum: Montag, 20. Mai 2019 um 09:20
An: plan-net/core4 <core4@noreply.github.com>
Cc: Michael Rau <M.Rau@plan-net.com>, Assign <assign@noreply.github.com>
Betreff: Re: [plan-net/core4] top left menu item in widget manager (#35)


on Production or localhost?

**Comment by marekmru** [comment]
core4ui hasn't been updated to the new version. Thats the reason for most problems.

**Comment by m-rau** [comment]
are there any special requirements to deployment for that or is this deployed automatically once updated?

**Comment by marekmru** [comment]
im inspecting this.

**Comment by marekmru** [comment]
Can you try it again. 
For localhost please remove the 
node_modules,
yarn.lock, 
package-lock 
folders/files in webapps/widgets.
For production it shoukd work automatically.

**Comment by m-rau** [comment]
fixed and worked locally. Not sure about production. I've added a built command "rm yarn.lock" to package.json.
