### ISSUE TITLE
username and password removed when creating user using a cookie

### ISSUE THREAD

**Issue by MarkusKral** [plan-net/core4#38]
branch: current develop

When trying to create a user (= role with email and password) using the api ('/core4/api/v1/roles'), the following steps are executed resulting in a removal of the password-information necessary to create a user.

within the post-request one can find the following lines:

`core4/api/v1/request/role/main.py`

```
        kwargs = dict(
            name=self.get_argument(
                "name", as_type=str),
            realname=self.get_argument(
                "realname", as_type=str, default=""),
            is_active=self.get_argument(
                "is_active", as_type=bool, default=True),
            role=self.get_argument(
                "role", as_type=list, default=[]),
            email=self.get_argument(
                "email", as_type=str, default=None),
            password=self.get_argument(
                "password", as_type=str, default=None, remove=False),
            perm=self.get_argument(
                "perm", as_type=list, default=[])
        )
```

password will always be ''None'' when one uses a cookie for authentication.

Before reaching above statement, core4 tries to verify the user of the request:

`core4/api/v1/request/main.py`

```
  async def verify_user(self):
      ...
      if auth_header is not None:
      ...
      else:
          token = self.get_argument("token", default=None, remove=True)
          username = self.get_argument("username", default=None, remove=True)
          password = self.get_argument("password", default=None, remove=True)
              if token is not None:
                  source = ("token", "args")
              elif username and password:
                  source = ("username", "args")
              else:
                  source = ("token", "cookie")
                  token = self.get_secure_cookie("token")
```

The password will get loaded using get_argument with the remove=True flag,
which results in it getting removed from the request arguments.
Within the CoreRequestHandler, the now missing password argument, which had nothing to do with authentication has been removed and can not be accessed any longer.
Expected behaviour: password argument still accessible within the RequestHandler.

Same can be expected if using the username argument.

**Comment by m-rau** [comment]
pull request has been merged into branch `develop`.
Issues have been observed. Widget/Vue login mechanics do not comply with your modifications. 
## solution
Further amendments:
* replaced `password` parameter with `passwd` in role API
* adopted profile API
* adopted regression tests (success)

Fixed version in branch `develop`.
