### ISSUE TITLE
role management app:: automatic password by mail

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#56]
the following enhancements are required
* option to send email to user so that the user can define his own password

**Comment by MarkusKral** [comment]
Hi @m-rau ,

I'm not entirely sure on my approach here as there are a lot of locations that needed changing.
Also the configuration has been extended.

Please review and give me feedback!

Thanks!
Markus

**Comment by m-rau** [comment]
looks great. Deployment not working because template files not included in MANIFEST. Please fix and retest in aws

**Comment by MarkusKral** [comment]
Added appropriate lines to MANIFEST.
Successfully tested initial creation and password reset.

Closing this issue.
