### ISSUE TITLE
role management app: edit permissions

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#58]
editing permissions has issues:
* editing an existing permissions "doubles" the edit string

**Comment by m-rau** [comment]
@KralMar: please add info about app into api documentation. Please describe all new parameters, e.g. "distinct". Documentation is not complete, yet.

**Comment by MarkusKral** [comment]
Documentation has been adopted to the new possible parameter. 
Extended Examples. commit: 16d0a3e2155b0e6a695478b9e938c0feda26e0a9
Also the html-widget is mentionend within the help card now.

As only the documentation changed: directly pushed into develop.

**Comment by MarkusKral** [comment]
As for the behavior of "doubled" permission-strings:

This is vuetify cardbox behavior: https://vuetifyjs.com/en/components/combobox

I can not find a way around that, maybe @marekmru can help.

**Comment by marekmru** [comment]
https://github.com/plan-net/core4/pull/103

**Comment by MarkusKral** [comment]
Confirmed working.
Branch merged and deleted.
