### ISSUE TITLE
Wrong helper method in MVG Example

### ISSUE THREAD

**Issue by basteiz** [plan-net/core4#66]
https://core4os.readthedocs.io/en/latest/example/mvg.html

hard to find in documentation, wrong call in msg-Examples, maybe others. (execute vs launch)

**Comment by m-rau** [comment]
actually the method is called ``execute`` and not ``launch``.
An additional section on job development and debugging has been added to core4os documentation (branch develop). This section explains the use and purpose of the ``execute`` method.
