### ISSUE TITLE
Create core4os documentation on how to build and deploy a frontend 

### ISSUE THREAD

**Issue by KralMar** [plan-net/core4#71]
CORE4OS frontends need a proper documentation for:

1. CORE4OS Single Page Apps (based on webpack, vuejs, vuetify and core4ui)
2. Widgets (with some constraint technically open for all frontend technologies)

On how to:

1. Install needed dependencies for running them in the CORE4OS environment
2. A skeleton and step-by-step guide on how to develop such an app/widget using vuejs/templating including:
    * Dark/light theming
    * Build a static card
    * Build a dynamic card
    * link directly to Applications or use them within the WidgetManger inside an iframe
3. A setup routine similar to “vue initialise”
4. technically build
    * dependencies
    * tools
    * processes
5. run, develop and test

**Comment by marekmru** [comment]
Initial commit https://github.com/plan-net/core4/tree/mmr.c4os%2371

**Comment by marekmru** [comment]
Feature has been merged into <develop>
