### ISSUE TITLE
Define custom navigation targets of the app manager

### ISSUE THREAD

**Issue by KralMar** [plan-net/core4#73]
One should be able to design additional html-elements/pages that get appended to each page/widget/app. Examples are imprint/privacy policy or help pages. 
Certain app manager elements (e.g. the top navigation) should be customizable and be able to specify custom endpoints to deliver the content of these links.

NEXT STEP:
* Define and agree on the concept

**Comment by m-rau** [comment]
Suggested solution is to reuse existing components:

## custom content implementation

Custom content is to be implemented as a simple endpoint delivering static content. 

Definition of a static file handler, e.g. from core4/api/v1/request/_content with a file about.html in this folder. The following static file handler will deliver all files out of this folder, e.g. ``http://domain/core4/api/v1/content/about.html``

```
        (r'/content', CoreStaticFileHandler, {
            "path": "/api/v1/request/request/_content",
            "static_path": "/api/v1/request(_content",
            "title": "core4os static content", "protected": True
        })
```

## define custom menu

The mapping of menu items to endpoint is to be specified in ``core4.yaml``. This solution allows to customise the deployment by setting a custom core4os configuration, e.g. at ``/etc/core4/local.yaml``.

The custom menu configuration is to be delivered to the FE. Suggestion is to use the existing ``/setting`` endpoint. This requires the mapping between menu items and endpoint as in the following example (see core4.yaml):

```
user_setting:
   _general:
     language: EN
     menu:
       About this App Manager: /home4/api/v1/about
       Imprint: /home4/api/v1/imprint
       Privacy Protection: /home4/api/v1/privacy
```

To access the custom configuration the FE addresses ``http://domain/core4/api/v1/setting/_general/menu

**Comment by marekmru** [comment]
From my point of view this is fine. It is extensible and covers the need for additional items.

**Comment by m-rau** [comment]
please watch this: modification of the default user settings requires an update in current regression tests. To be more specific: to make tests successful, the (default) navigation must be included into the expected results. For example ``tests/api/test_setting.py::test_default_settings_override``

**Comment by marekmru** [comment]
Teh widget sidebra target wasnt included - is fixed now in Resolved in mmr.c4os#21_2

**Comment by m-rau** [comment]
I will merge and test. Need to consider #81

**Comment by m-rau** [comment]
merged and tested. The following issues have been identified:
# #81 is rejected. Refactoring the navigation configuration from dict to list is the solution
# bug identified: the custom link is not working. It seems that rather the key than the value is populated as the link (``About`` instead of ``/about``).

**Comment by m-rau** [comment]
assigned to @marekmru for fixing and refactoring

**Comment by marekmru** [comment]
No this is just the internal mapping. What happens on the page is:

const path = (this.menu.find(val => val.label === type) || {}).path

soo there is a lookup on the path for the iframe

**Comment by m-rau** [comment]
I will retest when  the current pull requests are merged into develop and ready for testing
