### ISSUE TITLE
upgrade to Python 3.7 and pandas 0.25

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#84]

**Comment by MarkusKral** [comment]
Upgrading core4os to python3.7 would require only minimal changes.

However, this would break our support for standard debian9 installations, as python3.7 is not available for debian9 via default repositories.

One would have to compile python3.7 manually, including compiling a newer version of openssl first, which is required in version 1.1.1, but only 1.1.0 is required by default.

This could pose an obstacle for all users not proficient in using the cli.

todo:
Discuss:

- upgrade python manually anyway - extend debian install documentation
- dropping support for debian9 in favor of a newer version
- skipping the upgrade altogether (some packages e.g. googleads-python-lib do require a python version > 3.5)

**Comment by m-rau** [comment]
I prefer to upgrade. Do you have the required steps or a valid web resource at hand to build it?

**Comment by MarkusKral** [comment]
pull request for a small test-change: /pull/89

tests working for versions of python>=3.5.

pandas installs in version 0.25 already, due to setup.py: pandas >= 0.23

**Comment by m-rau** [comment]
pull  has been merged and tested. closed.
