### ISSUE TITLE
Resetting and intially setting password

### ISSUE THREAD

**Issue by MarkusKral** [plan-net/core4#86]
When setting a initial password or resetting a password via the frontend (domain/#/reset) one can successfully set a new/initial password. 

But: No success-feedback is provided to the user after klicking the "Request" button.
The user hast to manually redirect to the login-page. Also he does not know whether the password reset was successful.

**Comment by marekmru** [comment]
Added success message. The user has to use the 'BAack  to login' button.
To receive the changes:
- delete node_modules and yarn.lock
- install fe deps with 'yarn'

**Comment by m-rau** [comment]
What is the status here? Please provide an update.

**Comment by MarkusKral** [comment]
This has been fixed within core4ui commit: be241c3e6a45d64654cbbd8a0d90d9bba808c111

Closing this issue.
