### ISSUE TITLE
Migrate core4 webapps

### ISSUE THREAD

**Issue by marekmru** [plan-net/core4#93]
After the upgrade to vuetify 2.0 #70  all running core4os frontends should be also updated:

- Widget manager :white_check_mark:
- Comoco :white_check_mark:
- Aqis :white_check_mark:
- SalesAdvisor :white_check_mark:
- Tv Reporting :x:

Together with the upgrade we should also consider the #91

**Comment by marekmru** [comment]
@m-rau @OlhaTodorashko  fyi

**Comment by marekmru** [comment]
- v-list-tile(*) :arrow_right: v-list-item(*)
- <button flat :arrow_right: <button text
- tooltip slot syntax changed:
`  <v-tooltip bottom>
      <template v-slot:activator="{ on }">
        <v-btn color="primary" dark v-on="on">Button</v-btn>
      </template>
      <span>Tooltip</span>
    </v-tooltip>`  
- v-list-tile-sub-title  :arrow_right: - v-list-item-**subtitle**

**Comment by marekmru** [comment]
package.json:

- from   
`"dependencies": {
    "core4ui": "https://github.com/plan-net/core4ui.git#0.8.0"
  },`
- to
`  "dependencies": {
    "core4ui": "https://github.com/plan-net/core4ui.git#0.9.0"
  },`

**Comment by OlhaTodorashko** [comment]
"dependencies": { "core4ui": "^1.0.0" }
